name: Deploy to Server

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH to Prod server & create app folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "installing required folder and packages"
            sudo apt-get update
            sudo apt-get install docker.io docker-compose-v2 -y

            sudo usermod -aG docker $USER
            newgrp docker

            mkdir -p devops

      - name: Copy Docker Compose File
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: ~/devops

      - name: SSH to Prod server & run the app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "Starting deployment"

            
            export DOCKERHUB_USER=${{ vars.DOCKERHUB_USER }}
            export DOCKER_TAG=${{ github.sha }}

            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ vars.DOCKERHUB_USER }} --password-stdin

            cd ~/devops
            docker compose down
            docker compose up -d --build --force-recreate --pull always