name: hello_Avnish

on:
  workflow_dispatch: 

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello Avnish
        run: echo "Hello Avnish"

      - name: Say hello to username
        run: echo "Hello $USER"
